# Generated by Django 4.0.1 on 2022-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Номер заказа')),
                ('name', models.CharField(max_length=128, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=128, verbose_name='Номер телефона заказчика')),
                ('mail', models.CharField(max_length=128, verbose_name='Почта заказчика')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='Адресс заказчика')),
                ('goods', models.TextField(verbose_name='Список с элементами из 2 позиций: \n 1 - id товара \n 2 -  число товаров данного типа')),
                ('price', models.IntegerField(verbose_name='Стоимость заказа')),
                ('delivery', models.CharField(choices=[('courier', 'курьер'), ('client', 'самовывоз')], max_length=128, verbose_name='Способ доставки')),
                ('payment', models.CharField(choices=[('card', 'карта'), ('cash', 'наличные')], max_length=128, verbose_name='Способ оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category', models.CharField(choices=[('jacket', 'Пальто|куртки'), ('costume', 'Костюмы'), ('pullover', 'Свитера'), ('blazer', 'Блейзеры'), ('shirt', 'Рубашки'), ('jeans', 'Джинсы'), ('trousers', 'Брюки'), ('shorts', 'Шорты'), ('shoes', 'Обувь'), ('bag', 'Сумки|рюкзаки'), ('accessories', 'Аксессуары')], max_length=128, verbose_name='Категория')),
                ('sale', models.BooleanField(verbose_name='Участие в распродаже')),
                ('new_col', models.BooleanField(verbose_name='Новая коллекция')),
                ('image_path', models.CharField(max_length=512, verbose_name='Путь у изображению товара')),
            ],
        ),
    ]
